Elevator
Team6479/2020-cadathon pull request #7
Opened 2020-04-23 23:26 UTC by tishyac3141

2020-04-23 23:28 UTC, 2stinkysocks commented on src/main/java/frc/robot/subsystems/Elevator.java
> +  public void ascend(){
To keep Leo happy, add a space before the opening bracket on all of the methods in this class.

2020-04-23 23:33 UTC, leomwilson requested changes
Other than the comments I made, looks good

2020-04-23 23:33 UTC, leomwilson commented on src/main/java/frc/robot/commands/AscendToTop.java
> +    return false;
This needs to have a termination condition, probably a top limit switch.

2020-04-23 23:33 UTC, leomwilson commented on src/main/java/frc/robot/commands/DescendToBottom.java
> +    return false;
Same here, should probably use a bottom limit switch.

2020-04-24 22:26 UTC, leomwilson approved these changes
All good

2020-04-24 22:27 UTC, merged